---
title: "GLOBAL ECONOMY GDP GROWTH 2015-2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinythemes)
library(plotly)
library(dygraphs)
```

```{r}
setwd("C:/Users/ESM/Desktop/GDP Growth 1")
data<-read.csv("eco croissance.csv")
fluidPage(theme = shinytheme("united"))
data<-as.data.frame(data)
```


GLOBAL STATISTICS
==============


Row {data-height= 200}
-----------------------------------

```{r}
h4("The COVID-19 pandemic resulted in the most severe and synchronized decline in growth rates 
recorded in the world since World War II. According to current forecasts, more than 
90 per cent of the world's countries will experience a contraction in per capita gross domestic product (GDP) in 
2020 - higher than the 85% of countries in recession at the height of the Great Depression. In sub-Saharan Africa, the economic impact of the pandemic has been severe, although 
the virus did not spread as much as initially expected.1
 Uncertainty persists, as the health crisis is not 
not finished. The region cannot let its guard down. There are a lot of resources that need to be 
to strengthen African health systems and effectively protect staff 
while ensuring rapid and affordable health care for citizens.")


renderDygraph(dygraph(data, x=~data[[input$pays]]))
```

### Representative table of the development of the growth of the countries for the periods indicated.

```{r}
renderDataTable(data)

mainPanel("Change in Economic Growth According Selected Country ")


renderPlotly(plot_ly(data, x=~data[[input$pays]]))
```

GROWTH EVOLUTION
===========

```{r}
sidebarPanel(h5("Since the end of 2019, the development of countries' growth has started to decline. however there is no other explanation than the effect of the pendemie negatively affects the level of production of the countries
."))
```

Row {data-height= 150}
-------------------------------------------
```{r}
selectInput("pays", "Choose the country to see the evolution of its growth
", choices = c("USA","Chine","Haïti", "Italie", "France", "Espagne","Japon", "Canada"))

renderPlotly(plot_ly(data, x=~data[[input$pays]], color = I("Orange")))

```

Row {data-height= 150}
-----------------------------------
```{r}
selectInput("var", "Select another Country to Compare the level of the growth", choices = c("USA","Chine","Haïti", "Italie", "France", "Espagne","Japon", "Canada"))
renderPlotly(plot_ly(data, x=~data[[input$var]], color = I("green",type="scatter")))
```

```{r}
"llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll"
```

COUNTRIES GROWTH PROFILE
===================

```{r}
h4("On peut constater la croissance de tout les pays suivants on tandances a diminuer aucours de la 4e periode, l'annes 2019")
```

```{r}
plot(data$Monde, type = "l")
plot(data$France,type = "l")
plot(data$Chine, type = "l")
plot(data$Italie, type = "l")
plot(data$Espagne, type = "l")
plot(data$Union.Européenne,type = "l")

```

 DEPLOYERS INFORMATION
===========================

    Telephone: +509 3321323
    Mail: widnerlafleur@gmail.com
  
    ```{R}
    h4("This project was carried out with the aim of allowing to use it to play with the data in order to compare the evolution of the economic growth of the countries.
.")
    ```

-------------------------------------
    Realise par:
    LAFLEUR Pierre-Widner
    MOISE Gracita Emie
    INNOCENT Maika Smine
    
    
  
